const countriesData = [
  { code: 'PL', name: 'Polska' },
  { code: 'DE', name: 'Niemcy' },
  { code: 'FR', name: 'Francja' },
  { code: 'ES', name: 'Hiszpania' },
  { code: 'IT', name: 'Włochy' },
  { code: 'GB', name: 'Wielka Brytania' },
  { code: 'US', name: 'Stany Zjednoczone' },
  { code: 'CA', name: 'Kanada' },
  { code: 'JP', name: 'Japonia' },
  { code: 'AU', name: 'Australia' },
  { code: 'BR', name: 'Brazylia' },
  { code: 'AR', name: 'Argentyna' },
  { code: 'CN', name: 'Chiny' },
  { code: 'IN', name: 'Indie' },
  { code: 'ID', name: 'Indonezja' },
  { code: 'MX', name: 'Meksyk' },
  { code: 'NL', name: 'Holandia' },
  { code: 'BE', name: 'Belgia' },
  { code: 'CH', name: 'Szwajcaria' },
  { code: 'SE', name: 'Szwecja' },
  { code: 'NO', name: 'Norwegia' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'DK', name: 'Dania' },
  { code: 'PT', name: 'Portugalia' },
  { code: 'GR', name: 'Grecja' },
  { code: 'TR', name: 'Turcja' },
  { code: 'RU', name: 'Rosja' },
  { code: 'ZA', name: 'Południowa Afryka' },
  { code: 'EG', name: 'Egipt' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenia' },
  { code: 'SA', name: 'Arabia Saudyjska' },
  { code: 'AE', name: 'Zjednoczone Emiraty Arabskie' },
  { code: 'IL', name: 'Izrael' },
  { code: 'KR', name: 'Korea Południowa' },
  { code: 'TH', name: 'Tajlandia' },
  { code: 'VN', name: 'Wietnam' },
  { code: 'MY', name: 'Malezja' },
  { code: 'SG', name: 'Singapur' },
  { code: 'PH', name: 'Filipiny' },
  { code: 'NZ', name: 'Nowa Zelandia' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Kolumbia' },
  { code: 'PE', name: 'Peru' },
  { code: 'VE', name: 'Wenezuela' },
  { code: 'IE', name: 'Irlandia' },
  { code: 'AT', name: 'Austria' },
  { code: 'HU', name: 'Węgry' },
  { code: 'CZ', name: 'Czechy' },
  { code: 'SK', name: 'Słowacja' },
  { code: 'RO', name: 'Rumunia' },
  { code: 'BG', name: 'Bułgaria' },
  { code: 'HR', name: 'Chorwacja' },
  { code: 'SI', name: 'Słowenia' },
  { code: 'LT', name: 'Litwa' },
  { code: 'LV', name: 'Łotwa' },
  { code: 'EE', name: 'Estonia' },
  { code: 'UA', name: 'Ukraina' },
  { code: 'BY', name: 'Białoruś' },
  { code: 'IS', name: 'Islandia' },
  { code: 'LU', name: 'Luksemburg' }
];

exports.seed = async function (knex) {
  await knex('countries').del();
  await knex('countries').insert(countriesData);
};